language: cpp
script: make unit
dist: trusty

matrix:
  include:
    
    - os: linux
      dist: xenial
      language: r
      r: devel

      before_install:
        - R -e 'install.packages(c("DBI", "testthat", "DBItest"),repos=c("http://cran.rstudio.com/"))'
        - cd tools/rpkg

      install:
        -  R CMD INSTALL .

      before_script:
        - cd tests

      script:
        - R -f testthat.R

before_install:
    - eval "${MATRIX_EVAL}"
