language: cpp
script: make unit
dist: trusty

before_install:
  - eval "${MATRIX_EVAL}"

env:
  global:
    - CIBW_BUILD='cp37-* cp27-*'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_BEFORE_BUILD='pip install "numpy>=1.16" && pip install "pandas>=0.24" && pip install "pytest>=4.3" && pip install cmake==3.13.3'
    - CIBW_TEST_COMMAND='python -m pytest {project}/tests'


matrix:
  include:

    - os: linux
      dist: xenial
      name: GCC 5 (ARM64)
      arch: arm64

      script:
        - mkdir -p build/debug
        - (cd build/debug && cmake -DEXPLICIT_EXCEPTIONS=TRUE -DCMAKE_BUILD_TYPE=Debug ../.. && cmake --build .)
        - build/debug/test/unittest -s


    - os: linux
      name: GCC 4.9
      addons:
         apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9 binutils-2.26
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
