env:
  global:
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_BEFORE_BUILD='pip install --prefer-binary "pandas>=0.24" "pytest>=4.3"'
    - CIBW_TEST_COMMAND='python -m pytest {project}/tests'
    - SETUPTOOLS_SCM_NO_LOCAL=yes
    - TWINE_USERNAME=hfmuehleisen
    - SETUPTOOLS_SCM_DEBUG=please
    - MAKEFLAGS="-j 2"

git:
  depth: false

matrix:
  include:

    - os: linux
      name: Python 3.8 Package
      #if: (branch !~ ^r/.*$ AND head_branch !~ ^r/.*$)

      dist: bionic
      language: python
      cache: pip
      env:
        - CIBW_BUILD='cp38-*'
      python: 3.7

      install:
        - pip install cibuildwheel==1.5.5 twine

      script:
        - sudo python3 --version
        - cd tools/pythonpkg
        - python setup.py sdist
        - mkdir duckdb_tarball && tar xvf dist/duckdb-*.tar.gz --strip-components=1 -C duckdb_tarball
        - cibuildwheel --output-dir wheelhouse duckdb_tarball
        - cd ../..

        - |
          if [[ $TRAVIS_TAG ]] || ([ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]) ; then
            python -m twine upload --non-interactive --disable-progress-bar --skip-existing tools/pythonpkg/wheelhouse/*.whl
          fi


