on: [push]

jobs:
  win-release:
    name: Windows Release
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install
      run: choco install python3 --version 3.7.3 -y --params "/InstallDir:C:\Python37-x64"

    - name: Build
      shell: bash
      run: C:/Python37-x64/python.exe scripts/amalgamation.py && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 && cmake --build . --target duckdb --config Release

    - name: Test
      run: test/Release/unittest.exe

     
  xcode-release:
    name: OSX Release
    runs-on: macos-latest
    
    env:
      BUILD_ICU_EXTENSION: 1
      BUILD_TPCH_EXTENSION: 1
      BUILD_REST: 1
      JDBC_DRIVER: 1

    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: make

    - name: Test
      shell: bash
      run: make allunit
      
  xcode-debug:
    name: OSX Debug
    runs-on: macos-latest
    
    env:
      TREAT_WARNINGS_AS_ERRORS: 1
      DISABLE_UNITY: 1

    steps:
    - uses: actions/checkout@v2
  
    - name: Build
      shell: bash
      run: make debug

    - name: Test
      shell: bash
      run: make unit
      
  gcc-release:
    name: GCC10 Release
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_ICU_EXTENSION: 1
      BUILD_TPCH_EXTENSION: 1
      BUILD_REST: 1
      JDBC_DRIVER: 1

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      shell: bash
      run: sudo apt-get install ninja-build

    - name: Build
      shell: bash
      run: make

    - name: Test
      shell: bash
      run: make allunit
      
      
  gcc-debug:
    name: GCC10 Debug
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10
      TREAT_WARNINGS_AS_ERRORS: 1
      DISABLE_UNITY: 1
      GEN: ninja

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      shell: bash
      run: sudo apt-get install ninja-build

    - name: Build
      shell: bash
      run: make debug

    - name: Test
      shell: bash
      run: make unit
