on: [push]

jobs:
  win-debug:
    name: Windows Debug
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_GENERATOR_PLATFORM=x64 -DISABLE_UNITY=1 -DBUILD_ICU_EXTENSION=1 -DBUILD_PARQUET_EXTENSION=1 -DBUILD_TPCH_EXTENSION=1 -DBUILD_REST=1 -DJDBC_DRIVER=1 && cmake --build . --target unittest --config Debug

    - name: Test
      shell: bash
      run: test/Debug/unittest.exe

  win-release:
    name: Windows Release
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DBUILD_ICU_EXTENSION=1 -DBUILD_PARQUET_EXTENSION=1 -DBUILD_TPCH_EXTENSION=1 -DBUILD_REST=1 -DJDBC_DRIVER=1 && cmake --build . --target unittest --config Release

    - name: Test
      shell: bash
      run: test/Release/unittest.exe

     
  xcode-release:
    name: OSX Release
    runs-on: macos-latest
    
    env:
      BUILD_ICU_EXTENSION: 1
      BUILD_TPCH_EXTENSION: 1
      BUILD_REST: 1
      JDBC_DRIVER: 1

    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: make

    - name: Unit Test
      shell: bash
      run: make allunit

    - name: Tools Tests
      shell: bash
      run: python3 tools/shell/shell-test.py build/release/duckdb && python3 tools/rest/test_the_rest.py build/release/tools/rest && java -cp build/release/tools/jdbc/duckdb_jdbc.jar org.duckdb.test.TestDuckDBJDBC
      
  xcode-debug:
    name: OSX Debug
    runs-on: macos-latest
    
    env:
      TREAT_WARNINGS_AS_ERRORS: 1
      DISABLE_UNITY: 1

    steps:
    - uses: actions/checkout@v2
  
    - name: Build
      shell: bash
      run: make debug

    - name: Test
      shell: bash
      run: make unit
      
  gcc-release:
    name: GCC10 Release
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_ICU_EXTENSION: 1
      BUILD_TPCH_EXTENSION: 1
      BUILD_REST: 1
      JDBC_DRIVER: 1

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      shell: bash
      run: sudo apt-get install ninja-build

    - name: Build
      shell: bash
      run: make

    - name: Test
      shell: bash
      run: make allunit

    - name: Tools Tests
      shell: bash
      run: python3 tools/shell/shell-test.py build/release/duckdb && python3 tools/rest/test_the_rest.py build/release/tools/rest && java -cp build/release/tools/jdbc/duckdb_jdbc.jar org.duckdb.test.TestDuckDBJDBC
      
      
      
  gcc-debug:
    name: GCC10 Debug
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10
      TREAT_WARNINGS_AS_ERRORS: 1
      DISABLE_UNITY: 1
      GEN: ninja

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      shell: bash
      run: sudo apt-get install ninja-build

    - name: Build
      shell: bash
      run: make debug

    - name: Test
      shell: bash
      run: make unit
