on: [push, pull_request]

defaults:
  needs: linux-debug
  run:
    shell: bash

jobs:

  linux-debug:
    name: Linux Debug
    runs-on: ubuntu-latest
    needs: 
    
    env:
      CC: gcc-10
      CXX: g++-10
      TREAT_WARNINGS_AS_ERRORS: 1
      DISABLE_UNITY: 1
      GEN: ninja

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: sudo apt-get install ninja-build

    - name: Build
      run: make debug

    - name: Test
      run: make unit


  win-debug:
    name: Windows Debug
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_GENERATOR_PLATFORM=x64 -DISABLE_UNITY=1 -DBUILD_ICU_EXTENSION=1 -DBUILD_PARQUET_EXTENSION=1 -DBUILD_TPCH_EXTENSION=1 -DBUILD_REST=1 -DJDBC_DRIVER=1
        cmake --build . --target unittest --config Debug

    - name: Test
      run: test/Debug/unittest.exe


  win-release:
    name: Windows Release
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
      
    - name: Build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DBUILD_ICU_EXTENSION=1 -DBUILD_PARQUET_EXTENSION=1 -DBUILD_TPCH_EXTENSION=1 -DBUILD_REST=1 -DJDBC_DRIVER=1
        cmake --build . --target duckdb --config Release
        cmake --build . --target unittest --config Release
        cmake --build . --target shell --config Release
        cmake --build . --target jdbc --config Release

    - name: Test
      run: test/Release/unittest.exe

    - name: Tools Test
      run: |
        python tools/shell/shell-test.py Release/duckdb.exe
        java -cp tools/jdbc/duckdb_jdbc.jar org.duckdb.test.TestDuckDBJDBC

    - name: Packaging and Upload
      run: |
        choco install zip -y --force
        zip -j duckdb_cli-windows-amd64.zip Release/duckdb.exe
        zip -j libduckdb-windows-amd64.zip src/Release/duckdb.dll src/amalgamation/duckdb.hpp src/include/duckdb.h

     
  xcode-release:
    name: OSX Release
    runs-on: macos-latest
    
    env:
      BUILD_ICU: 1
      BUILD_TPCH: 1
      BUILD_REST: 1
      BUILD_JDBC: 1

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Build
      run: make

    - name: Unit Test
      run: make allunit

    - name: Tools Tests
      run: |
        python tools/shell/shell-test.py build/release/duckdb
        java -cp build/release/tools/jdbc/duckdb_jdbc.jar org.duckdb.test.TestDuckDBJDBC

    - name: Examples
      run: |
        (cd examples/embedded-c; make)
        (cd examples/embedded-c++; make)
        (cd examples/jdbc; make; make maven)

    - name: Packaging and Upload
      run: |
        zip -j duckdb_cli-osx-amd64.zip build/release/duckdb
        zip -j libduckdb-osx-amd64.zip build/release/src/libduckdb*.dylib src/amalgamation/duckdb.hpp src/include/duckdb.h


  xcode-debug:
    name: OSX Debug
    runs-on: macos-latest
    
    env:
      TREAT_WARNINGS_AS_ERRORS: 1
      DISABLE_UNITY: 1

    steps:
    - uses: actions/checkout@v2
  
    - name: Build
      run: make debug

    - name: Test
      run: make unit
      

  linux-release:
    name: Linux Release
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_ICU: 1
      BUILD_TPCH: 1
      BUILD_REST: 1
      BUILD_JDBC: 1

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    
    - name: Install
      run: sudo apt-get install ninja-build

    - name: Build
      run: make

    - name: Test
      run: make allunit

    - name: Tools Tests
      run: |
        python tools/shell/shell-test.py build/release/duckdb
        pip install requests
        python tools/rest/test_the_rest.py build/release/tools/rest
        java -cp build/release/tools/jdbc/duckdb_jdbc.jar org.duckdb.test.TestDuckDBJDBC

    - name: Examples
      run: |
        (cd examples/embedded-c; make)
        (cd examples/embedded-c++; make)
        (cd examples/jdbc; make; make maven)

    - name: Packaging and Upload
      run: |
        zip -j duckdb_cli-linux-amd64.zip build/release/duckdb
        zip -j libduckdb-linux-amd64.zip build/release/src/libduckdb*.so src/amalgamation/duckdb.hpp src/include/duckdb.h
        zip -j libduckdb-src.zip src/amalgamation/duckdb.hpp src/amalgamation/duckdb.cpp src/include/duckdb.h


  valgrind:
    name: Valgrind
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10
      DISABLE_SANITIZER: 1
      GEN: ninja

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: sudo apt-get install ninja-build valgrind

    - name: Build
      run: make debug

    - name: Test
      run: valgrind ./build/debug/test/unittest -s "Test TPC-H SF0.01"


  ubsan:
    name: UBSAN
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: sudo apt-get install ninja-build

    - name: Test
      run: make ubsandebug


  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    
    - name: Install
      run: pip install --user cpp-coveralls


    - name: Coverage
      run: |
        mkdir -p build/coverage
        (cd build/coverage && cmake -E env CXXFLAGS="--coverage" cmake -DCMAKE_BUILD_TYPE=Debug ../.. && make)
        build/coverage/test/unittest
        coveralls -b build/coverage --exclude-pattern '.*CMake.*' --exclude tools --exclude benchmark --exclude examples --exclude third_party --exclude test --exclude src/common/enums --exclude src/parser/transform/helpers/nodetype_to_string.cpp --exclude build/coverage/third_party/libpg_query --exclude build/coverage/third_party/libpg_query/grammar --gcov-options '\-lp' > /dev/null


  vector-sizes:
    name: Vector Sizes
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Test
      run: python scripts/test_vector_sizes.py


  sqllogic:
    name: Sqllogic tests
    runs-on: ubuntu-latest
    
    env:
      CC: gcc-10
      CXX: g++-10

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: make sqlite
