on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:

  python-36:
    name: Python Package
    runs-on: ubuntu-latest
    
    needs: linux-debug

    env:
      CIBW_BUILD='cp36-* cp37-* cp38-*'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    
    - name: Install
      run: pip install cibuildwheel twine

    - name: Build
      run: |
        cd tools/pythonpkg
        python setup.py sdist
        mkdir duckdb_tarball && tar xvf dist/duckdb-*.tar.gz --strip-components=1 -C duckdb_tarball
        cibuildwheel --output-dir wheelhouse duckdb_tarball
        cd ../..
        python scripts/asset-upload.py duckdb_python_src.tar.gz=tools/pythonpkg/dist/duckdb-*.tar.gz

      #  TODO python -m twine upload --non-interactive --disable-progress-bar --skip-existing tools/pythonpkg/wheelhouse/*.whl

